/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as NoteChar123NoteIdChar125RouteImport } from './routes/note.{-$noteId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteChar123NoteIdChar125Route =
  NoteChar123NoteIdChar125RouteImport.update({
    id: '/note/{-$noteId}',
    path: '/note/{-$noteId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/notes': typeof NotesRoute
  '/setup': typeof SetupRoute
  '/note/{-$noteId}': typeof NoteChar123NoteIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/notes': typeof NotesRoute
  '/setup': typeof SetupRoute
  '/note/{-$noteId}': typeof NoteChar123NoteIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/notes': typeof NotesRoute
  '/setup': typeof SetupRoute
  '/note/{-$noteId}': typeof NoteChar123NoteIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/notes' | '/setup' | '/note/{-$noteId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/notes' | '/setup' | '/note/{-$noteId}'
  id: '__root__' | '/' | '/about' | '/notes' | '/setup' | '/note/{-$noteId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NotesRoute: typeof NotesRoute
  SetupRoute: typeof SetupRoute
  NoteChar123NoteIdChar125Route: typeof NoteChar123NoteIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/{-$noteId}': {
      id: '/note/{-$noteId}'
      path: '/note/{-$noteId}'
      fullPath: '/note/{-$noteId}'
      preLoaderRoute: typeof NoteChar123NoteIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NotesRoute: NotesRoute,
  SetupRoute: SetupRoute,
  NoteChar123NoteIdChar125Route: NoteChar123NoteIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
